### ISSUE TITLE
LiveShortcutsView.xaml.cs missing from recent commit

### ISSUE THREAD

**Issue by ryanmolden** [justcla/VSShortcutsManager#12]
See title :)

**Comment by justcla** [comment]
Really?

This file: https://github.com/justcla/VSShortcutsManager/blob/master/VSShortcutsManager/LiveShortcutsView.xaml.cs
?

**Comment by mathicse** [comment]
I just checked in the missing .cs file

**Comment by justcla** [comment]
Fixed
